
* Article Information                                        :ignore:journal:

#+BEGIN_EXPORT latex
\JournalInfo{Nota de Conjuntura No 17} % Journal information
\Archive{} % Additional notes (e.g. copyright, DOI, review/research article)

\Authors{Pedro Paulo Zahluth Bastos\textsuperscript{1}*, Gabriel Petrini\textsuperscript{2}, Lorena Dourado\textsuperscript{3}} % Authors
\affiliation{\textsuperscript{1}\textit{Professor do Instituto de Economia Unicamp}} % Author affiliation
\affiliation{\textsuperscript{2}\textit{Doutorando do Instituto de Economia  Unicamp}} % Author affiliation
\affiliation{\textsuperscript{3}\textit{Graduanda do Instituto de Economia Unicamp}} % Author affiliation
\affiliation{*\textbf{E-mail}: ppzbastos@gmail.com} % Corresponding author

\newcommand{\keywordname}{Palavras-chave} % Defines the keywords heading name

\Abstract{
\begin{itemize}
\item O PIB do Brasil em 2020 reforça o consenso científico que beira a unanimidade: é a pandemia que deprime a economia, e não as iniciativas de saúde pública capazes de controlá-la. A contração da economia e da mobilidade voluntária precederam ações de distanciamento social estritas, que chegaram atrasadas para controlar os vários picos da pandemia e, assim, criar condições para recuperação econômica sustentada.
\item A bibliografia internacional sobre o impacto econômico da pandemia indica que ações de distanciamento social moderadas têm grande impacto econômico negativo que reforça o efeito do distanciamento voluntário, mas não são eficientes para reduzir a taxa de crescimento das infecções. Já ações de distanciamento social estritas conseguem sim reduzir as infecções, mas tem impacto econômico negativo pequeno na margem, pois a maior parte do impacto já tinha sido produzido pelo distanciamento voluntário e pela ação de distanciamento social moderada.
\item A conclusão é óbvia: ao invés de ficar parado torcendo para que a economia não despenque – pois ela vai despencar mesmo sem lockdowns rigorosos -, é melhor decretar lockdowns rigorosos o mais cedo possível, acompanhando-o de ações para evitar novos surtos (testagem, rastreio de contatos e isolamento seletivo). Assim, a redução brusca das infecções pode criar condições epidemiológicas para uma recuperação econômica sustentada, pois enquanto houver
risco de infecção haverá distanciamento voluntário. A médio prazo, portanto, não há conflito entre atividade econômica e controle da pandemia.
\item A economia brasileira confirma o padrão internacional. Estimamos o distanciamento social voluntário avaliando dados de mobilidade nos estados brasileiros e comparando-os com alterações nas ações de distanciamento social. Em muitos estados há sincronia quase perfeita entre as curvas de mobilidade e de número de casos independentemente de mudanças significativas na ação de distanciamento social, o que se explica pelo distanciamento voluntário.
\item Em razão do distanciamento voluntário, a recuperação econômica iniciada no terceiro trimestre desacelerou no quarto antes mesmo da interrupção do auxílio emergencial. A pandemia, tornando-se endemia, limitou a retomada da demanda e do emprego em serviços no último trimestre em razão dos riscos de transmissão, a despeito do relaxamento das ações de distanciamento social. Logo, tanto o distanciamento social quanto as políticas de defesa da renda foram mitigadas ou suspendidas cedo demais, e não foram acompanhadas nem sucedidas por ações para evitar novos surtos (testagem, rastreio de contatos e isolamento seletivo) por falta de coordenação nacional.
\item Como esperado, o recrudescimento da pandemia em 2021 foi novamente acompanhado da piora dos dados de mobilidade e dos indicadores econômicos. O indicador da OCDE para a semana concluída em 03 de abril de 2021 aponta para uma contração de 7,5\%, uma deterioração de 6 p.p. em menos de dois meses que leva o índice ao patamar do final de julho de 2020, quando ocorria o primeiro pico da pandemia em São Paulo e no Rio de Janeiro.
\item A gravidade da conjuntura aumenta a urgência da combinação de políticas de saúde pública com nova rodada de estímulos fiscais. Tal rodada deveria ser muito superior à retomada do auxílio emergencial em 06 de abril, que estimamos representar um choque negativo de 3\% do PIB em relação aos valores de 2020.
\item Sem controle da pandemia, a economia brasileira deve participar timidamente, na melhor das hipóteses, da recuperação do PIB dos grandes parceiros comerciais que ampliam a vacinação e controlam a pandemia em 2021. A pior das hipóteses, contudo, é cada vez mais provável.
\end{itemize}
}
\renewcommand{\abstractname}{Sumário Executivo} % Defines the keywords heading name
#+END_EXPORT
